# docker compose file for postgres and nodejs api server
# and get a init script for the database to create the tables and insert the data
# from script.sql

version: '3.7'
services:
  db:
    image: postgres:12
    container_name: db
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    image: node:12
    container_name: api
    restart: always
    ports:
      - 3001:3000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5433
    volumes:
      - ./:/app
    working_dir: /app
    command: npm start
    depends_on:
      - db