
version: '3.7'
services:
  db-jogos:
    image: postgres:12
    container_name: db-jogos
    restart: always
    ports:
      - '5430:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    image: folows/node-t2:latest
    container_name: api
    ports:
      - '8087:8087'
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - db-jogos