name: Dockerize Node.js application

on: push

jobs:
  build-container:
    name: Build Docker container image
    runs-on: ubuntu-latest
    steps:
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: folows/node-t2
          tags: latest, ${{ github.run_number }}